/*
 * SPDX-FileCopyrightText: 2019-2025 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __HPSYS_RCC_H
#define __HPSYS_RCC_H

typedef struct
{
    __IO uint32_t RSTR1;
    __IO uint32_t RSTR2;
    __IO uint32_t ENR1;
    __IO uint32_t ENR2;
    __IO uint32_t ESR1;
    __IO uint32_t ESR2;
    __IO uint32_t ECR1;
    __IO uint32_t ECR2;
    __IO uint32_t CSR;
    __IO uint32_t CFGR;
    __IO uint32_t USBCR;
    __IO uint32_t DLL1CR;
    __IO uint32_t DLL2CR;
    __IO uint32_t HRCCAL1;
    __IO uint32_t HRCCAL2;
    __IO uint32_t DBGCLKR;
    __IO uint32_t DBGR;
    __IO uint32_t DWCFGR;
    __IO uint32_t RSVD1[13];
    __IO uint32_t TESTR;
} HPSYS_RCC_TypeDef;


/**************** Bit definition for HPSYS_RCC_RSTR1 register *****************/
#define HPSYS_RCC_RSTR1_DMAC1_Pos       (0U)
#define HPSYS_RCC_RSTR1_DMAC1_Msk       (0x1UL << HPSYS_RCC_RSTR1_DMAC1_Pos)
#define HPSYS_RCC_RSTR1_DMAC1           HPSYS_RCC_RSTR1_DMAC1_Msk
#define HPSYS_RCC_RSTR1_MAILBOX1_Pos    (1U)
#define HPSYS_RCC_RSTR1_MAILBOX1_Msk    (0x1UL << HPSYS_RCC_RSTR1_MAILBOX1_Pos)
#define HPSYS_RCC_RSTR1_MAILBOX1        HPSYS_RCC_RSTR1_MAILBOX1_Msk
#define HPSYS_RCC_RSTR1_PINMUX1_Pos     (2U)
#define HPSYS_RCC_RSTR1_PINMUX1_Msk     (0x1UL << HPSYS_RCC_RSTR1_PINMUX1_Pos)
#define HPSYS_RCC_RSTR1_PINMUX1         HPSYS_RCC_RSTR1_PINMUX1_Msk
#define HPSYS_RCC_RSTR1_USART1_Pos      (3U)
#define HPSYS_RCC_RSTR1_USART1_Msk      (0x1UL << HPSYS_RCC_RSTR1_USART1_Pos)
#define HPSYS_RCC_RSTR1_USART1          HPSYS_RCC_RSTR1_USART1_Msk
#define HPSYS_RCC_RSTR1_USART2_Pos      (4U)
#define HPSYS_RCC_RSTR1_USART2_Msk      (0x1UL << HPSYS_RCC_RSTR1_USART2_Pos)
#define HPSYS_RCC_RSTR1_USART2          HPSYS_RCC_RSTR1_USART2_Msk
#define HPSYS_RCC_RSTR1_EZIP1_Pos       (5U)
#define HPSYS_RCC_RSTR1_EZIP1_Msk       (0x1UL << HPSYS_RCC_RSTR1_EZIP1_Pos)
#define HPSYS_RCC_RSTR1_EZIP1           HPSYS_RCC_RSTR1_EZIP1_Msk
#define HPSYS_RCC_RSTR1_EPIC_Pos        (6U)
#define HPSYS_RCC_RSTR1_EPIC_Msk        (0x1UL << HPSYS_RCC_RSTR1_EPIC_Pos)
#define HPSYS_RCC_RSTR1_EPIC            HPSYS_RCC_RSTR1_EPIC_Msk
#define HPSYS_RCC_RSTR1_LCDC1_Pos       (7U)
#define HPSYS_RCC_RSTR1_LCDC1_Msk       (0x1UL << HPSYS_RCC_RSTR1_LCDC1_Pos)
#define HPSYS_RCC_RSTR1_LCDC1           HPSYS_RCC_RSTR1_LCDC1_Msk
#define HPSYS_RCC_RSTR1_I2S1_Pos        (8U)
#define HPSYS_RCC_RSTR1_I2S1_Msk        (0x1UL << HPSYS_RCC_RSTR1_I2S1_Pos)
#define HPSYS_RCC_RSTR1_I2S1            HPSYS_RCC_RSTR1_I2S1_Msk
#define HPSYS_RCC_RSTR1_SYSCFG1_Pos     (10U)
#define HPSYS_RCC_RSTR1_SYSCFG1_Msk     (0x1UL << HPSYS_RCC_RSTR1_SYSCFG1_Pos)
#define HPSYS_RCC_RSTR1_SYSCFG1         HPSYS_RCC_RSTR1_SYSCFG1_Msk
#define HPSYS_RCC_RSTR1_EFUSEC_Pos      (11U)
#define HPSYS_RCC_RSTR1_EFUSEC_Msk      (0x1UL << HPSYS_RCC_RSTR1_EFUSEC_Pos)
#define HPSYS_RCC_RSTR1_EFUSEC          HPSYS_RCC_RSTR1_EFUSEC_Msk
#define HPSYS_RCC_RSTR1_AES_Pos         (12U)
#define HPSYS_RCC_RSTR1_AES_Msk         (0x1UL << HPSYS_RCC_RSTR1_AES_Pos)
#define HPSYS_RCC_RSTR1_AES             HPSYS_RCC_RSTR1_AES_Msk
#define HPSYS_RCC_RSTR1_CRC1_Pos        (13U)
#define HPSYS_RCC_RSTR1_CRC1_Msk        (0x1UL << HPSYS_RCC_RSTR1_CRC1_Pos)
#define HPSYS_RCC_RSTR1_CRC1            HPSYS_RCC_RSTR1_CRC1_Msk
#define HPSYS_RCC_RSTR1_TRNG_Pos        (14U)
#define HPSYS_RCC_RSTR1_TRNG_Msk        (0x1UL << HPSYS_RCC_RSTR1_TRNG_Pos)
#define HPSYS_RCC_RSTR1_TRNG            HPSYS_RCC_RSTR1_TRNG_Msk
#define HPSYS_RCC_RSTR1_GPTIM1_Pos      (15U)
#define HPSYS_RCC_RSTR1_GPTIM1_Msk      (0x1UL << HPSYS_RCC_RSTR1_GPTIM1_Pos)
#define HPSYS_RCC_RSTR1_GPTIM1          HPSYS_RCC_RSTR1_GPTIM1_Msk
#define HPSYS_RCC_RSTR1_GPTIM2_Pos      (16U)
#define HPSYS_RCC_RSTR1_GPTIM2_Msk      (0x1UL << HPSYS_RCC_RSTR1_GPTIM2_Pos)
#define HPSYS_RCC_RSTR1_GPTIM2          HPSYS_RCC_RSTR1_GPTIM2_Msk
#define HPSYS_RCC_RSTR1_BTIM1_Pos       (17U)
#define HPSYS_RCC_RSTR1_BTIM1_Msk       (0x1UL << HPSYS_RCC_RSTR1_BTIM1_Pos)
#define HPSYS_RCC_RSTR1_BTIM1           HPSYS_RCC_RSTR1_BTIM1_Msk
#define HPSYS_RCC_RSTR1_BTIM2_Pos       (18U)
#define HPSYS_RCC_RSTR1_BTIM2_Msk       (0x1UL << HPSYS_RCC_RSTR1_BTIM2_Pos)
#define HPSYS_RCC_RSTR1_BTIM2           HPSYS_RCC_RSTR1_BTIM2_Msk
#define HPSYS_RCC_RSTR1_SPI1_Pos        (20U)
#define HPSYS_RCC_RSTR1_SPI1_Msk        (0x1UL << HPSYS_RCC_RSTR1_SPI1_Pos)
#define HPSYS_RCC_RSTR1_SPI1            HPSYS_RCC_RSTR1_SPI1_Msk
#define HPSYS_RCC_RSTR1_SPI2_Pos        (21U)
#define HPSYS_RCC_RSTR1_SPI2_Msk        (0x1UL << HPSYS_RCC_RSTR1_SPI2_Pos)
#define HPSYS_RCC_RSTR1_SPI2            HPSYS_RCC_RSTR1_SPI2_Msk
#define HPSYS_RCC_RSTR1_EXTDMA_Pos      (22U)
#define HPSYS_RCC_RSTR1_EXTDMA_Msk      (0x1UL << HPSYS_RCC_RSTR1_EXTDMA_Pos)
#define HPSYS_RCC_RSTR1_EXTDMA          HPSYS_RCC_RSTR1_EXTDMA_Msk
#define HPSYS_RCC_RSTR1_PDM1_Pos        (25U)
#define HPSYS_RCC_RSTR1_PDM1_Msk        (0x1UL << HPSYS_RCC_RSTR1_PDM1_Pos)
#define HPSYS_RCC_RSTR1_PDM1            HPSYS_RCC_RSTR1_PDM1_Msk
#define HPSYS_RCC_RSTR1_I2C1_Pos        (27U)
#define HPSYS_RCC_RSTR1_I2C1_Msk        (0x1UL << HPSYS_RCC_RSTR1_I2C1_Pos)
#define HPSYS_RCC_RSTR1_I2C1            HPSYS_RCC_RSTR1_I2C1_Msk
#define HPSYS_RCC_RSTR1_I2C2_Pos        (28U)
#define HPSYS_RCC_RSTR1_I2C2_Msk        (0x1UL << HPSYS_RCC_RSTR1_I2C2_Pos)
#define HPSYS_RCC_RSTR1_I2C2            HPSYS_RCC_RSTR1_I2C2_Msk
#define HPSYS_RCC_RSTR1_PTC1_Pos        (31U)
#define HPSYS_RCC_RSTR1_PTC1_Msk        (0x1UL << HPSYS_RCC_RSTR1_PTC1_Pos)
#define HPSYS_RCC_RSTR1_PTC1            HPSYS_RCC_RSTR1_PTC1_Msk

/**************** Bit definition for HPSYS_RCC_RSTR2 register *****************/
#define HPSYS_RCC_RSTR2_GPIO1_Pos       (0U)
#define HPSYS_RCC_RSTR2_GPIO1_Msk       (0x1UL << HPSYS_RCC_RSTR2_GPIO1_Pos)
#define HPSYS_RCC_RSTR2_GPIO1           HPSYS_RCC_RSTR2_GPIO1_Msk
#define HPSYS_RCC_RSTR2_MPI1_Pos        (1U)
#define HPSYS_RCC_RSTR2_MPI1_Msk        (0x1UL << HPSYS_RCC_RSTR2_MPI1_Pos)
#define HPSYS_RCC_RSTR2_MPI1            HPSYS_RCC_RSTR2_MPI1_Msk
#define HPSYS_RCC_RSTR2_MPI2_Pos        (2U)
#define HPSYS_RCC_RSTR2_MPI2_Msk        (0x1UL << HPSYS_RCC_RSTR2_MPI2_Pos)
#define HPSYS_RCC_RSTR2_MPI2            HPSYS_RCC_RSTR2_MPI2_Msk
#define HPSYS_RCC_RSTR2_SDMMC1_Pos      (4U)
#define HPSYS_RCC_RSTR2_SDMMC1_Msk      (0x1UL << HPSYS_RCC_RSTR2_SDMMC1_Pos)
#define HPSYS_RCC_RSTR2_SDMMC1          HPSYS_RCC_RSTR2_SDMMC1_Msk
#define HPSYS_RCC_RSTR2_USBC_Pos        (6U)
#define HPSYS_RCC_RSTR2_USBC_Msk        (0x1UL << HPSYS_RCC_RSTR2_USBC_Pos)
#define HPSYS_RCC_RSTR2_USBC            HPSYS_RCC_RSTR2_USBC_Msk
#define HPSYS_RCC_RSTR2_I2C3_Pos        (8U)
#define HPSYS_RCC_RSTR2_I2C3_Msk        (0x1UL << HPSYS_RCC_RSTR2_I2C3_Pos)
#define HPSYS_RCC_RSTR2_I2C3            HPSYS_RCC_RSTR2_I2C3_Msk
#define HPSYS_RCC_RSTR2_ATIM1_Pos       (9U)
#define HPSYS_RCC_RSTR2_ATIM1_Msk       (0x1UL << HPSYS_RCC_RSTR2_ATIM1_Pos)
#define HPSYS_RCC_RSTR2_ATIM1           HPSYS_RCC_RSTR2_ATIM1_Msk
#define HPSYS_RCC_RSTR2_USART3_Pos      (12U)
#define HPSYS_RCC_RSTR2_USART3_Msk      (0x1UL << HPSYS_RCC_RSTR2_USART3_Pos)
#define HPSYS_RCC_RSTR2_USART3          HPSYS_RCC_RSTR2_USART3_Msk
#define HPSYS_RCC_RSTR2_AUDCODEC_Pos    (19U)
#define HPSYS_RCC_RSTR2_AUDCODEC_Msk    (0x1UL << HPSYS_RCC_RSTR2_AUDCODEC_Pos)
#define HPSYS_RCC_RSTR2_AUDCODEC        HPSYS_RCC_RSTR2_AUDCODEC_Msk
#define HPSYS_RCC_RSTR2_AUDPRC_Pos      (20U)
#define HPSYS_RCC_RSTR2_AUDPRC_Msk      (0x1UL << HPSYS_RCC_RSTR2_AUDPRC_Pos)
#define HPSYS_RCC_RSTR2_AUDPRC          HPSYS_RCC_RSTR2_AUDPRC_Msk
#define HPSYS_RCC_RSTR2_GPADC_Pos       (22U)
#define HPSYS_RCC_RSTR2_GPADC_Msk       (0x1UL << HPSYS_RCC_RSTR2_GPADC_Pos)
#define HPSYS_RCC_RSTR2_GPADC           HPSYS_RCC_RSTR2_GPADC_Msk
#define HPSYS_RCC_RSTR2_TSEN_Pos        (23U)
#define HPSYS_RCC_RSTR2_TSEN_Msk        (0x1UL << HPSYS_RCC_RSTR2_TSEN_Pos)
#define HPSYS_RCC_RSTR2_TSEN            HPSYS_RCC_RSTR2_TSEN_Msk
#define HPSYS_RCC_RSTR2_I2C4_Pos        (25U)
#define HPSYS_RCC_RSTR2_I2C4_Msk        (0x1UL << HPSYS_RCC_RSTR2_I2C4_Pos)
#define HPSYS_RCC_RSTR2_I2C4            HPSYS_RCC_RSTR2_I2C4_Msk

/***************** Bit definition for HPSYS_RCC_ENR1 register *****************/
#define HPSYS_RCC_ENR1_DMAC1_Pos        (0U)
#define HPSYS_RCC_ENR1_DMAC1_Msk        (0x1UL << HPSYS_RCC_ENR1_DMAC1_Pos)
#define HPSYS_RCC_ENR1_DMAC1            HPSYS_RCC_ENR1_DMAC1_Msk
#define HPSYS_RCC_ENR1_MAILBOX1_Pos     (1U)
#define HPSYS_RCC_ENR1_MAILBOX1_Msk     (0x1UL << HPSYS_RCC_ENR1_MAILBOX1_Pos)
#define HPSYS_RCC_ENR1_MAILBOX1         HPSYS_RCC_ENR1_MAILBOX1_Msk
#define HPSYS_RCC_ENR1_PINMUX1_Pos      (2U)
#define HPSYS_RCC_ENR1_PINMUX1_Msk      (0x1UL << HPSYS_RCC_ENR1_PINMUX1_Pos)
#define HPSYS_RCC_ENR1_PINMUX1          HPSYS_RCC_ENR1_PINMUX1_Msk
#define HPSYS_RCC_ENR1_USART2_Pos       (4U)
#define HPSYS_RCC_ENR1_USART2_Msk       (0x1UL << HPSYS_RCC_ENR1_USART2_Pos)
#define HPSYS_RCC_ENR1_USART2           HPSYS_RCC_ENR1_USART2_Msk
#define HPSYS_RCC_ENR1_EZIP1_Pos        (5U)
#define HPSYS_RCC_ENR1_EZIP1_Msk        (0x1UL << HPSYS_RCC_ENR1_EZIP1_Pos)
#define HPSYS_RCC_ENR1_EZIP1            HPSYS_RCC_ENR1_EZIP1_Msk
#define HPSYS_RCC_ENR1_EPIC_Pos         (6U)
#define HPSYS_RCC_ENR1_EPIC_Msk         (0x1UL << HPSYS_RCC_ENR1_EPIC_Pos)
#define HPSYS_RCC_ENR1_EPIC             HPSYS_RCC_ENR1_EPIC_Msk
#define HPSYS_RCC_ENR1_LCDC1_Pos        (7U)
#define HPSYS_RCC_ENR1_LCDC1_Msk        (0x1UL << HPSYS_RCC_ENR1_LCDC1_Pos)
#define HPSYS_RCC_ENR1_LCDC1            HPSYS_RCC_ENR1_LCDC1_Msk
#define HPSYS_RCC_ENR1_I2S1_Pos         (8U)
#define HPSYS_RCC_ENR1_I2S1_Msk         (0x1UL << HPSYS_RCC_ENR1_I2S1_Pos)
#define HPSYS_RCC_ENR1_I2S1             HPSYS_RCC_ENR1_I2S1_Msk
#define HPSYS_RCC_ENR1_SYSCFG1_Pos      (10U)
#define HPSYS_RCC_ENR1_SYSCFG1_Msk      (0x1UL << HPSYS_RCC_ENR1_SYSCFG1_Pos)
#define HPSYS_RCC_ENR1_SYSCFG1          HPSYS_RCC_ENR1_SYSCFG1_Msk
#define HPSYS_RCC_ENR1_EFUSEC_Pos       (11U)
#define HPSYS_RCC_ENR1_EFUSEC_Msk       (0x1UL << HPSYS_RCC_ENR1_EFUSEC_Pos)
#define HPSYS_RCC_ENR1_EFUSEC           HPSYS_RCC_ENR1_EFUSEC_Msk
#define HPSYS_RCC_ENR1_AES_Pos          (12U)
#define HPSYS_RCC_ENR1_AES_Msk          (0x1UL << HPSYS_RCC_ENR1_AES_Pos)
#define HPSYS_RCC_ENR1_AES              HPSYS_RCC_ENR1_AES_Msk
#define HPSYS_RCC_ENR1_CRC1_Pos         (13U)
#define HPSYS_RCC_ENR1_CRC1_Msk         (0x1UL << HPSYS_RCC_ENR1_CRC1_Pos)
#define HPSYS_RCC_ENR1_CRC1             HPSYS_RCC_ENR1_CRC1_Msk
#define HPSYS_RCC_ENR1_TRNG_Pos         (14U)
#define HPSYS_RCC_ENR1_TRNG_Msk         (0x1UL << HPSYS_RCC_ENR1_TRNG_Pos)
#define HPSYS_RCC_ENR1_TRNG             HPSYS_RCC_ENR1_TRNG_Msk
#define HPSYS_RCC_ENR1_GPTIM1_Pos       (15U)
#define HPSYS_RCC_ENR1_GPTIM1_Msk       (0x1UL << HPSYS_RCC_ENR1_GPTIM1_Pos)
#define HPSYS_RCC_ENR1_GPTIM1           HPSYS_RCC_ENR1_GPTIM1_Msk
#define HPSYS_RCC_ENR1_GPTIM2_Pos       (16U)
#define HPSYS_RCC_ENR1_GPTIM2_Msk       (0x1UL << HPSYS_RCC_ENR1_GPTIM2_Pos)
#define HPSYS_RCC_ENR1_GPTIM2           HPSYS_RCC_ENR1_GPTIM2_Msk
#define HPSYS_RCC_ENR1_BTIM1_Pos        (17U)
#define HPSYS_RCC_ENR1_BTIM1_Msk        (0x1UL << HPSYS_RCC_ENR1_BTIM1_Pos)
#define HPSYS_RCC_ENR1_BTIM1            HPSYS_RCC_ENR1_BTIM1_Msk
#define HPSYS_RCC_ENR1_BTIM2_Pos        (18U)
#define HPSYS_RCC_ENR1_BTIM2_Msk        (0x1UL << HPSYS_RCC_ENR1_BTIM2_Pos)
#define HPSYS_RCC_ENR1_BTIM2            HPSYS_RCC_ENR1_BTIM2_Msk
#define HPSYS_RCC_ENR1_SPI1_Pos         (20U)
#define HPSYS_RCC_ENR1_SPI1_Msk         (0x1UL << HPSYS_RCC_ENR1_SPI1_Pos)
#define HPSYS_RCC_ENR1_SPI1             HPSYS_RCC_ENR1_SPI1_Msk
#define HPSYS_RCC_ENR1_SPI2_Pos         (21U)
#define HPSYS_RCC_ENR1_SPI2_Msk         (0x1UL << HPSYS_RCC_ENR1_SPI2_Pos)
#define HPSYS_RCC_ENR1_SPI2             HPSYS_RCC_ENR1_SPI2_Msk
#define HPSYS_RCC_ENR1_EXTDMA_Pos       (22U)
#define HPSYS_RCC_ENR1_EXTDMA_Msk       (0x1UL << HPSYS_RCC_ENR1_EXTDMA_Pos)
#define HPSYS_RCC_ENR1_EXTDMA           HPSYS_RCC_ENR1_EXTDMA_Msk
#define HPSYS_RCC_ENR1_SECU1_Pos        (23U)
#define HPSYS_RCC_ENR1_SECU1_Msk        (0x1UL << HPSYS_RCC_ENR1_SECU1_Pos)
#define HPSYS_RCC_ENR1_SECU1            HPSYS_RCC_ENR1_SECU1_Msk
#define HPSYS_RCC_ENR1_PDM1_Pos         (25U)
#define HPSYS_RCC_ENR1_PDM1_Msk         (0x1UL << HPSYS_RCC_ENR1_PDM1_Pos)
#define HPSYS_RCC_ENR1_PDM1             HPSYS_RCC_ENR1_PDM1_Msk
#define HPSYS_RCC_ENR1_I2C1_Pos         (27U)
#define HPSYS_RCC_ENR1_I2C1_Msk         (0x1UL << HPSYS_RCC_ENR1_I2C1_Pos)
#define HPSYS_RCC_ENR1_I2C1             HPSYS_RCC_ENR1_I2C1_Msk
#define HPSYS_RCC_ENR1_I2C2_Pos         (28U)
#define HPSYS_RCC_ENR1_I2C2_Msk         (0x1UL << HPSYS_RCC_ENR1_I2C2_Pos)
#define HPSYS_RCC_ENR1_I2C2             HPSYS_RCC_ENR1_I2C2_Msk
#define HPSYS_RCC_ENR1_PTC1_Pos         (31U)
#define HPSYS_RCC_ENR1_PTC1_Msk         (0x1UL << HPSYS_RCC_ENR1_PTC1_Pos)
#define HPSYS_RCC_ENR1_PTC1             HPSYS_RCC_ENR1_PTC1_Msk

/***************** Bit definition for HPSYS_RCC_ENR2 register *****************/
#define HPSYS_RCC_ENR2_GPIO1_Pos        (0U)
#define HPSYS_RCC_ENR2_GPIO1_Msk        (0x1UL << HPSYS_RCC_ENR2_GPIO1_Pos)
#define HPSYS_RCC_ENR2_GPIO1            HPSYS_RCC_ENR2_GPIO1_Msk
#define HPSYS_RCC_ENR2_MPI1_Pos         (1U)
#define HPSYS_RCC_ENR2_MPI1_Msk         (0x1UL << HPSYS_RCC_ENR2_MPI1_Pos)
#define HPSYS_RCC_ENR2_MPI1             HPSYS_RCC_ENR2_MPI1_Msk
#define HPSYS_RCC_ENR2_MPI2_Pos         (2U)
#define HPSYS_RCC_ENR2_MPI2_Msk         (0x1UL << HPSYS_RCC_ENR2_MPI2_Pos)
#define HPSYS_RCC_ENR2_MPI2             HPSYS_RCC_ENR2_MPI2_Msk
#define HPSYS_RCC_ENR2_SDMMC1_Pos       (4U)
#define HPSYS_RCC_ENR2_SDMMC1_Msk       (0x1UL << HPSYS_RCC_ENR2_SDMMC1_Pos)
#define HPSYS_RCC_ENR2_SDMMC1           HPSYS_RCC_ENR2_SDMMC1_Msk
#define HPSYS_RCC_ENR2_USBC_Pos         (6U)
#define HPSYS_RCC_ENR2_USBC_Msk         (0x1UL << HPSYS_RCC_ENR2_USBC_Pos)
#define HPSYS_RCC_ENR2_USBC             HPSYS_RCC_ENR2_USBC_Msk
#define HPSYS_RCC_ENR2_I2C3_Pos         (8U)
#define HPSYS_RCC_ENR2_I2C3_Msk         (0x1UL << HPSYS_RCC_ENR2_I2C3_Pos)
#define HPSYS_RCC_ENR2_I2C3             HPSYS_RCC_ENR2_I2C3_Msk
#define HPSYS_RCC_ENR2_ATIM1_Pos        (9U)
#define HPSYS_RCC_ENR2_ATIM1_Msk        (0x1UL << HPSYS_RCC_ENR2_ATIM1_Pos)
#define HPSYS_RCC_ENR2_ATIM1            HPSYS_RCC_ENR2_ATIM1_Msk
#define HPSYS_RCC_ENR2_USART3_Pos       (12U)
#define HPSYS_RCC_ENR2_USART3_Msk       (0x1UL << HPSYS_RCC_ENR2_USART3_Pos)
#define HPSYS_RCC_ENR2_USART3           HPSYS_RCC_ENR2_USART3_Msk
#define HPSYS_RCC_ENR2_AUDCODEC_Pos     (19U)
#define HPSYS_RCC_ENR2_AUDCODEC_Msk     (0x1UL << HPSYS_RCC_ENR2_AUDCODEC_Pos)
#define HPSYS_RCC_ENR2_AUDCODEC         HPSYS_RCC_ENR2_AUDCODEC_Msk
#define HPSYS_RCC_ENR2_AUDPRC_Pos       (20U)
#define HPSYS_RCC_ENR2_AUDPRC_Msk       (0x1UL << HPSYS_RCC_ENR2_AUDPRC_Pos)
#define HPSYS_RCC_ENR2_AUDPRC           HPSYS_RCC_ENR2_AUDPRC_Msk
#define HPSYS_RCC_ENR2_GPADC_Pos        (22U)
#define HPSYS_RCC_ENR2_GPADC_Msk        (0x1UL << HPSYS_RCC_ENR2_GPADC_Pos)
#define HPSYS_RCC_ENR2_GPADC            HPSYS_RCC_ENR2_GPADC_Msk
#define HPSYS_RCC_ENR2_TSEN_Pos         (23U)
#define HPSYS_RCC_ENR2_TSEN_Msk         (0x1UL << HPSYS_RCC_ENR2_TSEN_Pos)
#define HPSYS_RCC_ENR2_TSEN             HPSYS_RCC_ENR2_TSEN_Msk
#define HPSYS_RCC_ENR2_I2C4_Pos         (25U)
#define HPSYS_RCC_ENR2_I2C4_Msk         (0x1UL << HPSYS_RCC_ENR2_I2C4_Pos)
#define HPSYS_RCC_ENR2_I2C4             HPSYS_RCC_ENR2_I2C4_Msk

/***************** Bit definition for HPSYS_RCC_ESR1 register *****************/
#define HPSYS_RCC_ESR1_DMAC1_Pos        (0U)
#define HPSYS_RCC_ESR1_DMAC1_Msk        (0x1UL << HPSYS_RCC_ESR1_DMAC1_Pos)
#define HPSYS_RCC_ESR1_DMAC1            HPSYS_RCC_ESR1_DMAC1_Msk
#define HPSYS_RCC_ESR1_MAILBOX1_Pos     (1U)
#define HPSYS_RCC_ESR1_MAILBOX1_Msk     (0x1UL << HPSYS_RCC_ESR1_MAILBOX1_Pos)
#define HPSYS_RCC_ESR1_MAILBOX1         HPSYS_RCC_ESR1_MAILBOX1_Msk
#define HPSYS_RCC_ESR1_PINMUX1_Pos      (2U)
#define HPSYS_RCC_ESR1_PINMUX1_Msk      (0x1UL << HPSYS_RCC_ESR1_PINMUX1_Pos)
#define HPSYS_RCC_ESR1_PINMUX1          HPSYS_RCC_ESR1_PINMUX1_Msk
#define HPSYS_RCC_ESR1_USART2_Pos       (4U)
#define HPSYS_RCC_ESR1_USART2_Msk       (0x1UL << HPSYS_RCC_ESR1_USART2_Pos)
#define HPSYS_RCC_ESR1_USART2           HPSYS_RCC_ESR1_USART2_Msk
#define HPSYS_RCC_ESR1_EZIP1_Pos        (5U)
#define HPSYS_RCC_ESR1_EZIP1_Msk        (0x1UL << HPSYS_RCC_ESR1_EZIP1_Pos)
#define HPSYS_RCC_ESR1_EZIP1            HPSYS_RCC_ESR1_EZIP1_Msk
#define HPSYS_RCC_ESR1_EPIC_Pos         (6U)
#define HPSYS_RCC_ESR1_EPIC_Msk         (0x1UL << HPSYS_RCC_ESR1_EPIC_Pos)
#define HPSYS_RCC_ESR1_EPIC             HPSYS_RCC_ESR1_EPIC_Msk
#define HPSYS_RCC_ESR1_LCDC1_Pos        (7U)
#define HPSYS_RCC_ESR1_LCDC1_Msk        (0x1UL << HPSYS_RCC_ESR1_LCDC1_Pos)
#define HPSYS_RCC_ESR1_LCDC1            HPSYS_RCC_ESR1_LCDC1_Msk
#define HPSYS_RCC_ESR1_I2S1_Pos         (8U)
#define HPSYS_RCC_ESR1_I2S1_Msk         (0x1UL << HPSYS_RCC_ESR1_I2S1_Pos)
#define HPSYS_RCC_ESR1_I2S1             HPSYS_RCC_ESR1_I2S1_Msk
#define HPSYS_RCC_ESR1_SYSCFG1_Pos      (10U)
#define HPSYS_RCC_ESR1_SYSCFG1_Msk      (0x1UL << HPSYS_RCC_ESR1_SYSCFG1_Pos)
#define HPSYS_RCC_ESR1_SYSCFG1          HPSYS_RCC_ESR1_SYSCFG1_Msk
#define HPSYS_RCC_ESR1_EFUSEC_Pos       (11U)
#define HPSYS_RCC_ESR1_EFUSEC_Msk       (0x1UL << HPSYS_RCC_ESR1_EFUSEC_Pos)
#define HPSYS_RCC_ESR1_EFUSEC           HPSYS_RCC_ESR1_EFUSEC_Msk
#define HPSYS_RCC_ESR1_AES_Pos          (12U)
#define HPSYS_RCC_ESR1_AES_Msk          (0x1UL << HPSYS_RCC_ESR1_AES_Pos)
#define HPSYS_RCC_ESR1_AES              HPSYS_RCC_ESR1_AES_Msk
#define HPSYS_RCC_ESR1_CRC1_Pos         (13U)
#define HPSYS_RCC_ESR1_CRC1_Msk         (0x1UL << HPSYS_RCC_ESR1_CRC1_Pos)
#define HPSYS_RCC_ESR1_CRC1             HPSYS_RCC_ESR1_CRC1_Msk
#define HPSYS_RCC_ESR1_TRNG_Pos         (14U)
#define HPSYS_RCC_ESR1_TRNG_Msk         (0x1UL << HPSYS_RCC_ESR1_TRNG_Pos)
#define HPSYS_RCC_ESR1_TRNG             HPSYS_RCC_ESR1_TRNG_Msk
#define HPSYS_RCC_ESR1_GPTIM1_Pos       (15U)
#define HPSYS_RCC_ESR1_GPTIM1_Msk       (0x1UL << HPSYS_RCC_ESR1_GPTIM1_Pos)
#define HPSYS_RCC_ESR1_GPTIM1           HPSYS_RCC_ESR1_GPTIM1_Msk
#define HPSYS_RCC_ESR1_GPTIM2_Pos       (16U)
#define HPSYS_RCC_ESR1_GPTIM2_Msk       (0x1UL << HPSYS_RCC_ESR1_GPTIM2_Pos)
#define HPSYS_RCC_ESR1_GPTIM2           HPSYS_RCC_ESR1_GPTIM2_Msk
#define HPSYS_RCC_ESR1_BTIM1_Pos        (17U)
#define HPSYS_RCC_ESR1_BTIM1_Msk        (0x1UL << HPSYS_RCC_ESR1_BTIM1_Pos)
#define HPSYS_RCC_ESR1_BTIM1            HPSYS_RCC_ESR1_BTIM1_Msk
#define HPSYS_RCC_ESR1_BTIM2_Pos        (18U)
#define HPSYS_RCC_ESR1_BTIM2_Msk        (0x1UL << HPSYS_RCC_ESR1_BTIM2_Pos)
#define HPSYS_RCC_ESR1_BTIM2            HPSYS_RCC_ESR1_BTIM2_Msk
#define HPSYS_RCC_ESR1_SPI1_Pos         (20U)
#define HPSYS_RCC_ESR1_SPI1_Msk         (0x1UL << HPSYS_RCC_ESR1_SPI1_Pos)
#define HPSYS_RCC_ESR1_SPI1             HPSYS_RCC_ESR1_SPI1_Msk
#define HPSYS_RCC_ESR1_SPI2_Pos         (21U)
#define HPSYS_RCC_ESR1_SPI2_Msk         (0x1UL << HPSYS_RCC_ESR1_SPI2_Pos)
#define HPSYS_RCC_ESR1_SPI2             HPSYS_RCC_ESR1_SPI2_Msk
#define HPSYS_RCC_ESR1_EXTDMA_Pos       (22U)
#define HPSYS_RCC_ESR1_EXTDMA_Msk       (0x1UL << HPSYS_RCC_ESR1_EXTDMA_Pos)
#define HPSYS_RCC_ESR1_EXTDMA           HPSYS_RCC_ESR1_EXTDMA_Msk
#define HPSYS_RCC_ESR1_SECU1_Pos        (23U)
#define HPSYS_RCC_ESR1_SECU1_Msk        (0x1UL << HPSYS_RCC_ESR1_SECU1_Pos)
#define HPSYS_RCC_ESR1_SECU1            HPSYS_RCC_ESR1_SECU1_Msk
#define HPSYS_RCC_ESR1_PDM1_Pos         (25U)
#define HPSYS_RCC_ESR1_PDM1_Msk         (0x1UL << HPSYS_RCC_ESR1_PDM1_Pos)
#define HPSYS_RCC_ESR1_PDM1             HPSYS_RCC_ESR1_PDM1_Msk
#define HPSYS_RCC_ESR1_I2C1_Pos         (27U)
#define HPSYS_RCC_ESR1_I2C1_Msk         (0x1UL << HPSYS_RCC_ESR1_I2C1_Pos)
#define HPSYS_RCC_ESR1_I2C1             HPSYS_RCC_ESR1_I2C1_Msk
#define HPSYS_RCC_ESR1_I2C2_Pos         (28U)
#define HPSYS_RCC_ESR1_I2C2_Msk         (0x1UL << HPSYS_RCC_ESR1_I2C2_Pos)
#define HPSYS_RCC_ESR1_I2C2             HPSYS_RCC_ESR1_I2C2_Msk
#define HPSYS_RCC_ESR1_PTC1_Pos         (31U)
#define HPSYS_RCC_ESR1_PTC1_Msk         (0x1UL << HPSYS_RCC_ESR1_PTC1_Pos)
#define HPSYS_RCC_ESR1_PTC1             HPSYS_RCC_ESR1_PTC1_Msk

/***************** Bit definition for HPSYS_RCC_ESR2 register *****************/
#define HPSYS_RCC_ESR2_GPIO1_Pos        (0U)
#define HPSYS_RCC_ESR2_GPIO1_Msk        (0x1UL << HPSYS_RCC_ESR2_GPIO1_Pos)
#define HPSYS_RCC_ESR2_GPIO1            HPSYS_RCC_ESR2_GPIO1_Msk
#define HPSYS_RCC_ESR2_MPI1_Pos         (1U)
#define HPSYS_RCC_ESR2_MPI1_Msk         (0x1UL << HPSYS_RCC_ESR2_MPI1_Pos)
#define HPSYS_RCC_ESR2_MPI1             HPSYS_RCC_ESR2_MPI1_Msk
#define HPSYS_RCC_ESR2_MPI2_Pos         (2U)
#define HPSYS_RCC_ESR2_MPI2_Msk         (0x1UL << HPSYS_RCC_ESR2_MPI2_Pos)
#define HPSYS_RCC_ESR2_MPI2             HPSYS_RCC_ESR2_MPI2_Msk
#define HPSYS_RCC_ESR2_SDMMC1_Pos       (4U)
#define HPSYS_RCC_ESR2_SDMMC1_Msk       (0x1UL << HPSYS_RCC_ESR2_SDMMC1_Pos)
#define HPSYS_RCC_ESR2_SDMMC1           HPSYS_RCC_ESR2_SDMMC1_Msk
#define HPSYS_RCC_ESR2_USBC_Pos         (6U)
#define HPSYS_RCC_ESR2_USBC_Msk         (0x1UL << HPSYS_RCC_ESR2_USBC_Pos)
#define HPSYS_RCC_ESR2_USBC             HPSYS_RCC_ESR2_USBC_Msk
#define HPSYS_RCC_ESR2_I2C3_Pos         (8U)
#define HPSYS_RCC_ESR2_I2C3_Msk         (0x1UL << HPSYS_RCC_ESR2_I2C3_Pos)
#define HPSYS_RCC_ESR2_I2C3             HPSYS_RCC_ESR2_I2C3_Msk
#define HPSYS_RCC_ESR2_ATIM1_Pos        (9U)
#define HPSYS_RCC_ESR2_ATIM1_Msk        (0x1UL << HPSYS_RCC_ESR2_ATIM1_Pos)
#define HPSYS_RCC_ESR2_ATIM1            HPSYS_RCC_ESR2_ATIM1_Msk
#define HPSYS_RCC_ESR2_USART3_Pos       (12U)
#define HPSYS_RCC_ESR2_USART3_Msk       (0x1UL << HPSYS_RCC_ESR2_USART3_Pos)
#define HPSYS_RCC_ESR2_USART3           HPSYS_RCC_ESR2_USART3_Msk
#define HPSYS_RCC_ESR2_AUDCODEC_Pos     (19U)
#define HPSYS_RCC_ESR2_AUDCODEC_Msk     (0x1UL << HPSYS_RCC_ESR2_AUDCODEC_Pos)
#define HPSYS_RCC_ESR2_AUDCODEC         HPSYS_RCC_ESR2_AUDCODEC_Msk
#define HPSYS_RCC_ESR2_AUDPRC_Pos       (20U)
#define HPSYS_RCC_ESR2_AUDPRC_Msk       (0x1UL << HPSYS_RCC_ESR2_AUDPRC_Pos)
#define HPSYS_RCC_ESR2_AUDPRC           HPSYS_RCC_ESR2_AUDPRC_Msk
#define HPSYS_RCC_ESR2_GPADC_Pos        (22U)
#define HPSYS_RCC_ESR2_GPADC_Msk        (0x1UL << HPSYS_RCC_ESR2_GPADC_Pos)
#define HPSYS_RCC_ESR2_GPADC            HPSYS_RCC_ESR2_GPADC_Msk
#define HPSYS_RCC_ESR2_TSEN_Pos         (23U)
#define HPSYS_RCC_ESR2_TSEN_Msk         (0x1UL << HPSYS_RCC_ESR2_TSEN_Pos)
#define HPSYS_RCC_ESR2_TSEN             HPSYS_RCC_ESR2_TSEN_Msk
#define HPSYS_RCC_ESR2_I2C4_Pos         (25U)
#define HPSYS_RCC_ESR2_I2C4_Msk         (0x1UL << HPSYS_RCC_ESR2_I2C4_Pos)
#define HPSYS_RCC_ESR2_I2C4             HPSYS_RCC_ESR2_I2C4_Msk

/***************** Bit definition for HPSYS_RCC_ECR1 register *****************/
#define HPSYS_RCC_ECR1_DMAC1_Pos        (0U)
#define HPSYS_RCC_ECR1_DMAC1_Msk        (0x1UL << HPSYS_RCC_ECR1_DMAC1_Pos)
#define HPSYS_RCC_ECR1_DMAC1            HPSYS_RCC_ECR1_DMAC1_Msk
#define HPSYS_RCC_ECR1_MAILBOX1_Pos     (1U)
#define HPSYS_RCC_ECR1_MAILBOX1_Msk     (0x1UL << HPSYS_RCC_ECR1_MAILBOX1_Pos)
#define HPSYS_RCC_ECR1_MAILBOX1         HPSYS_RCC_ECR1_MAILBOX1_Msk
#define HPSYS_RCC_ECR1_PINMUX1_Pos      (2U)
#define HPSYS_RCC_ECR1_PINMUX1_Msk      (0x1UL << HPSYS_RCC_ECR1_PINMUX1_Pos)
#define HPSYS_RCC_ECR1_PINMUX1          HPSYS_RCC_ECR1_PINMUX1_Msk
#define HPSYS_RCC_ECR1_USART2_Pos       (4U)
#define HPSYS_RCC_ECR1_USART2_Msk       (0x1UL << HPSYS_RCC_ECR1_USART2_Pos)
#define HPSYS_RCC_ECR1_USART2           HPSYS_RCC_ECR1_USART2_Msk
#define HPSYS_RCC_ECR1_EZIP1_Pos        (5U)
#define HPSYS_RCC_ECR1_EZIP1_Msk        (0x1UL << HPSYS_RCC_ECR1_EZIP1_Pos)
#define HPSYS_RCC_ECR1_EZIP1            HPSYS_RCC_ECR1_EZIP1_Msk
#define HPSYS_RCC_ECR1_EPIC_Pos         (6U)
#define HPSYS_RCC_ECR1_EPIC_Msk         (0x1UL << HPSYS_RCC_ECR1_EPIC_Pos)
#define HPSYS_RCC_ECR1_EPIC             HPSYS_RCC_ECR1_EPIC_Msk
#define HPSYS_RCC_ECR1_LCDC1_Pos        (7U)
#define HPSYS_RCC_ECR1_LCDC1_Msk        (0x1UL << HPSYS_RCC_ECR1_LCDC1_Pos)
#define HPSYS_RCC_ECR1_LCDC1            HPSYS_RCC_ECR1_LCDC1_Msk
#define HPSYS_RCC_ECR1_I2S1_Pos         (8U)
#define HPSYS_RCC_ECR1_I2S1_Msk         (0x1UL << HPSYS_RCC_ECR1_I2S1_Pos)
#define HPSYS_RCC_ECR1_I2S1             HPSYS_RCC_ECR1_I2S1_Msk
#define HPSYS_RCC_ECR1_SYSCFG1_Pos      (10U)
#define HPSYS_RCC_ECR1_SYSCFG1_Msk      (0x1UL << HPSYS_RCC_ECR1_SYSCFG1_Pos)
#define HPSYS_RCC_ECR1_SYSCFG1          HPSYS_RCC_ECR1_SYSCFG1_Msk
#define HPSYS_RCC_ECR1_EFUSEC_Pos       (11U)
#define HPSYS_RCC_ECR1_EFUSEC_Msk       (0x1UL << HPSYS_RCC_ECR1_EFUSEC_Pos)
#define HPSYS_RCC_ECR1_EFUSEC           HPSYS_RCC_ECR1_EFUSEC_Msk
#define HPSYS_RCC_ECR1_AES_Pos          (12U)
#define HPSYS_RCC_ECR1_AES_Msk          (0x1UL << HPSYS_RCC_ECR1_AES_Pos)
#define HPSYS_RCC_ECR1_AES              HPSYS_RCC_ECR1_AES_Msk
#define HPSYS_RCC_ECR1_CRC1_Pos         (13U)
#define HPSYS_RCC_ECR1_CRC1_Msk         (0x1UL << HPSYS_RCC_ECR1_CRC1_Pos)
#define HPSYS_RCC_ECR1_CRC1             HPSYS_RCC_ECR1_CRC1_Msk
#define HPSYS_RCC_ECR1_TRNG_Pos         (14U)
#define HPSYS_RCC_ECR1_TRNG_Msk         (0x1UL << HPSYS_RCC_ECR1_TRNG_Pos)
#define HPSYS_RCC_ECR1_TRNG             HPSYS_RCC_ECR1_TRNG_Msk
#define HPSYS_RCC_ECR1_GPTIM1_Pos       (15U)
#define HPSYS_RCC_ECR1_GPTIM1_Msk       (0x1UL << HPSYS_RCC_ECR1_GPTIM1_Pos)
#define HPSYS_RCC_ECR1_GPTIM1           HPSYS_RCC_ECR1_GPTIM1_Msk
#define HPSYS_RCC_ECR1_GPTIM2_Pos       (16U)
#define HPSYS_RCC_ECR1_GPTIM2_Msk       (0x1UL << HPSYS_RCC_ECR1_GPTIM2_Pos)
#define HPSYS_RCC_ECR1_GPTIM2           HPSYS_RCC_ECR1_GPTIM2_Msk
#define HPSYS_RCC_ECR1_BTIM1_Pos        (17U)
#define HPSYS_RCC_ECR1_BTIM1_Msk        (0x1UL << HPSYS_RCC_ECR1_BTIM1_Pos)
#define HPSYS_RCC_ECR1_BTIM1            HPSYS_RCC_ECR1_BTIM1_Msk
#define HPSYS_RCC_ECR1_BTIM2_Pos        (18U)
#define HPSYS_RCC_ECR1_BTIM2_Msk        (0x1UL << HPSYS_RCC_ECR1_BTIM2_Pos)
#define HPSYS_RCC_ECR1_BTIM2            HPSYS_RCC_ECR1_BTIM2_Msk
#define HPSYS_RCC_ECR1_SPI1_Pos         (20U)
#define HPSYS_RCC_ECR1_SPI1_Msk         (0x1UL << HPSYS_RCC_ECR1_SPI1_Pos)
#define HPSYS_RCC_ECR1_SPI1             HPSYS_RCC_ECR1_SPI1_Msk
#define HPSYS_RCC_ECR1_SPI2_Pos         (21U)
#define HPSYS_RCC_ECR1_SPI2_Msk         (0x1UL << HPSYS_RCC_ECR1_SPI2_Pos)
#define HPSYS_RCC_ECR1_SPI2             HPSYS_RCC_ECR1_SPI2_Msk
#define HPSYS_RCC_ECR1_EXTDMA_Pos       (22U)
#define HPSYS_RCC_ECR1_EXTDMA_Msk       (0x1UL << HPSYS_RCC_ECR1_EXTDMA_Pos)
#define HPSYS_RCC_ECR1_EXTDMA           HPSYS_RCC_ECR1_EXTDMA_Msk
#define HPSYS_RCC_ECR1_SECU1_Pos        (23U)
#define HPSYS_RCC_ECR1_SECU1_Msk        (0x1UL << HPSYS_RCC_ECR1_SECU1_Pos)
#define HPSYS_RCC_ECR1_SECU1            HPSYS_RCC_ECR1_SECU1_Msk
#define HPSYS_RCC_ECR1_PDM1_Pos         (25U)
#define HPSYS_RCC_ECR1_PDM1_Msk         (0x1UL << HPSYS_RCC_ECR1_PDM1_Pos)
#define HPSYS_RCC_ECR1_PDM1             HPSYS_RCC_ECR1_PDM1_Msk
#define HPSYS_RCC_ECR1_I2C1_Pos         (27U)
#define HPSYS_RCC_ECR1_I2C1_Msk         (0x1UL << HPSYS_RCC_ECR1_I2C1_Pos)
#define HPSYS_RCC_ECR1_I2C1             HPSYS_RCC_ECR1_I2C1_Msk
#define HPSYS_RCC_ECR1_I2C2_Pos         (28U)
#define HPSYS_RCC_ECR1_I2C2_Msk         (0x1UL << HPSYS_RCC_ECR1_I2C2_Pos)
#define HPSYS_RCC_ECR1_I2C2             HPSYS_RCC_ECR1_I2C2_Msk
#define HPSYS_RCC_ECR1_PTC1_Pos         (31U)
#define HPSYS_RCC_ECR1_PTC1_Msk         (0x1UL << HPSYS_RCC_ECR1_PTC1_Pos)
#define HPSYS_RCC_ECR1_PTC1             HPSYS_RCC_ECR1_PTC1_Msk

/***************** Bit definition for HPSYS_RCC_ECR2 register *****************/
#define HPSYS_RCC_ECR2_GPIO1_Pos        (0U)
#define HPSYS_RCC_ECR2_GPIO1_Msk        (0x1UL << HPSYS_RCC_ECR2_GPIO1_Pos)
#define HPSYS_RCC_ECR2_GPIO1            HPSYS_RCC_ECR2_GPIO1_Msk
#define HPSYS_RCC_ECR2_MPI1_Pos         (1U)
#define HPSYS_RCC_ECR2_MPI1_Msk         (0x1UL << HPSYS_RCC_ECR2_MPI1_Pos)
#define HPSYS_RCC_ECR2_MPI1             HPSYS_RCC_ECR2_MPI1_Msk
#define HPSYS_RCC_ECR2_MPI2_Pos         (2U)
#define HPSYS_RCC_ECR2_MPI2_Msk         (0x1UL << HPSYS_RCC_ECR2_MPI2_Pos)
#define HPSYS_RCC_ECR2_MPI2             HPSYS_RCC_ECR2_MPI2_Msk
#define HPSYS_RCC_ECR2_SDMMC1_Pos       (4U)
#define HPSYS_RCC_ECR2_SDMMC1_Msk       (0x1UL << HPSYS_RCC_ECR2_SDMMC1_Pos)
#define HPSYS_RCC_ECR2_SDMMC1           HPSYS_RCC_ECR2_SDMMC1_Msk
#define HPSYS_RCC_ECR2_USBC_Pos         (6U)
#define HPSYS_RCC_ECR2_USBC_Msk         (0x1UL << HPSYS_RCC_ECR2_USBC_Pos)
#define HPSYS_RCC_ECR2_USBC             HPSYS_RCC_ECR2_USBC_Msk
#define HPSYS_RCC_ECR2_I2C3_Pos         (8U)
#define HPSYS_RCC_ECR2_I2C3_Msk         (0x1UL << HPSYS_RCC_ECR2_I2C3_Pos)
#define HPSYS_RCC_ECR2_I2C3             HPSYS_RCC_ECR2_I2C3_Msk
#define HPSYS_RCC_ECR2_ATIM1_Pos        (9U)
#define HPSYS_RCC_ECR2_ATIM1_Msk        (0x1UL << HPSYS_RCC_ECR2_ATIM1_Pos)
#define HPSYS_RCC_ECR2_ATIM1            HPSYS_RCC_ECR2_ATIM1_Msk
#define HPSYS_RCC_ECR2_USART3_Pos       (12U)
#define HPSYS_RCC_ECR2_USART3_Msk       (0x1UL << HPSYS_RCC_ECR2_USART3_Pos)
#define HPSYS_RCC_ECR2_USART3           HPSYS_RCC_ECR2_USART3_Msk
#define HPSYS_RCC_ECR2_AUDCODEC_Pos     (19U)
#define HPSYS_RCC_ECR2_AUDCODEC_Msk     (0x1UL << HPSYS_RCC_ECR2_AUDCODEC_Pos)
#define HPSYS_RCC_ECR2_AUDCODEC         HPSYS_RCC_ECR2_AUDCODEC_Msk
#define HPSYS_RCC_ECR2_AUDPRC_Pos       (20U)
#define HPSYS_RCC_ECR2_AUDPRC_Msk       (0x1UL << HPSYS_RCC_ECR2_AUDPRC_Pos)
#define HPSYS_RCC_ECR2_AUDPRC           HPSYS_RCC_ECR2_AUDPRC_Msk
#define HPSYS_RCC_ECR2_GPADC_Pos        (22U)
#define HPSYS_RCC_ECR2_GPADC_Msk        (0x1UL << HPSYS_RCC_ECR2_GPADC_Pos)
#define HPSYS_RCC_ECR2_GPADC            HPSYS_RCC_ECR2_GPADC_Msk
#define HPSYS_RCC_ECR2_TSEN_Pos         (23U)
#define HPSYS_RCC_ECR2_TSEN_Msk         (0x1UL << HPSYS_RCC_ECR2_TSEN_Pos)
#define HPSYS_RCC_ECR2_TSEN             HPSYS_RCC_ECR2_TSEN_Msk
#define HPSYS_RCC_ECR2_I2C4_Pos         (25U)
#define HPSYS_RCC_ECR2_I2C4_Msk         (0x1UL << HPSYS_RCC_ECR2_I2C4_Pos)
#define HPSYS_RCC_ECR2_I2C4             HPSYS_RCC_ECR2_I2C4_Msk

/***************** Bit definition for HPSYS_RCC_CSR register ******************/
#define HPSYS_RCC_CSR_SEL_SYS_Pos       (0U)
#define HPSYS_RCC_CSR_SEL_SYS_Msk       (0x3UL << HPSYS_RCC_CSR_SEL_SYS_Pos)
#define HPSYS_RCC_CSR_SEL_SYS           HPSYS_RCC_CSR_SEL_SYS_Msk
#define HPSYS_RCC_CSR_SEL_SYS_LP_Pos    (2U)
#define HPSYS_RCC_CSR_SEL_SYS_LP_Msk    (0x1UL << HPSYS_RCC_CSR_SEL_SYS_LP_Pos)
#define HPSYS_RCC_CSR_SEL_SYS_LP        HPSYS_RCC_CSR_SEL_SYS_LP_Msk
#define HPSYS_RCC_CSR_SEL_MPI1_Pos      (4U)
#define HPSYS_RCC_CSR_SEL_MPI1_Msk      (0x3UL << HPSYS_RCC_CSR_SEL_MPI1_Pos)
#define HPSYS_RCC_CSR_SEL_MPI1          HPSYS_RCC_CSR_SEL_MPI1_Msk
#define HPSYS_RCC_CSR_SEL_MPI2_Pos      (6U)
#define HPSYS_RCC_CSR_SEL_MPI2_Msk      (0x3UL << HPSYS_RCC_CSR_SEL_MPI2_Pos)
#define HPSYS_RCC_CSR_SEL_MPI2          HPSYS_RCC_CSR_SEL_MPI2_Msk
#define HPSYS_RCC_CSR_SEL_PERI_Pos      (12U)
#define HPSYS_RCC_CSR_SEL_PERI_Msk      (0x1UL << HPSYS_RCC_CSR_SEL_PERI_Pos)
#define HPSYS_RCC_CSR_SEL_PERI          HPSYS_RCC_CSR_SEL_PERI_Msk
#define HPSYS_RCC_CSR_SEL_TICK_Pos      (13U)
#define HPSYS_RCC_CSR_SEL_TICK_Msk      (0x3UL << HPSYS_RCC_CSR_SEL_TICK_Pos)
#define HPSYS_RCC_CSR_SEL_TICK          HPSYS_RCC_CSR_SEL_TICK_Msk
#define HPSYS_RCC_CSR_SEL_USBC_Pos      (15U)
#define HPSYS_RCC_CSR_SEL_USBC_Msk      (0x1UL << HPSYS_RCC_CSR_SEL_USBC_Pos)
#define HPSYS_RCC_CSR_SEL_USBC          HPSYS_RCC_CSR_SEL_USBC_Msk

/***************** Bit definition for HPSYS_RCC_CFGR register *****************/
#define HPSYS_RCC_CFGR_HDIV_Pos         (0U)
#define HPSYS_RCC_CFGR_HDIV_Msk         (0xFFUL << HPSYS_RCC_CFGR_HDIV_Pos)
#define HPSYS_RCC_CFGR_HDIV             HPSYS_RCC_CFGR_HDIV_Msk
#define HPSYS_RCC_CFGR_PDIV1_Pos        (8U)
#define HPSYS_RCC_CFGR_PDIV1_Msk        (0x7UL << HPSYS_RCC_CFGR_PDIV1_Pos)
#define HPSYS_RCC_CFGR_PDIV1            HPSYS_RCC_CFGR_PDIV1_Msk
#define HPSYS_RCC_CFGR_PDIV2_Pos        (12U)
#define HPSYS_RCC_CFGR_PDIV2_Msk        (0x7UL << HPSYS_RCC_CFGR_PDIV2_Pos)
#define HPSYS_RCC_CFGR_PDIV2            HPSYS_RCC_CFGR_PDIV2_Msk
#define HPSYS_RCC_CFGR_TICKDIV_Pos      (16U)
#define HPSYS_RCC_CFGR_TICKDIV_Msk      (0x3FUL << HPSYS_RCC_CFGR_TICKDIV_Pos)
#define HPSYS_RCC_CFGR_TICKDIV          HPSYS_RCC_CFGR_TICKDIV_Msk

/**************** Bit definition for HPSYS_RCC_USBCR register *****************/
#define HPSYS_RCC_USBCR_DIV_Pos         (0U)
#define HPSYS_RCC_USBCR_DIV_Msk         (0x7UL << HPSYS_RCC_USBCR_DIV_Pos)
#define HPSYS_RCC_USBCR_DIV             HPSYS_RCC_USBCR_DIV_Msk

/**************** Bit definition for HPSYS_RCC_DLL1CR register ****************/
#define HPSYS_RCC_DLL1CR_EN_Pos         (0U)
#define HPSYS_RCC_DLL1CR_EN_Msk         (0x1UL << HPSYS_RCC_DLL1CR_EN_Pos)
#define HPSYS_RCC_DLL1CR_EN             HPSYS_RCC_DLL1CR_EN_Msk
#define HPSYS_RCC_DLL1CR_SW_Pos         (1U)
#define HPSYS_RCC_DLL1CR_SW_Msk         (0x1UL << HPSYS_RCC_DLL1CR_SW_Pos)
#define HPSYS_RCC_DLL1CR_SW             HPSYS_RCC_DLL1CR_SW_Msk
#define HPSYS_RCC_DLL1CR_STG_Pos        (2U)
#define HPSYS_RCC_DLL1CR_STG_Msk        (0xFUL << HPSYS_RCC_DLL1CR_STG_Pos)
#define HPSYS_RCC_DLL1CR_STG            HPSYS_RCC_DLL1CR_STG_Msk
#define HPSYS_RCC_DLL1CR_XTALIN_EN_Pos  (6U)
#define HPSYS_RCC_DLL1CR_XTALIN_EN_Msk  (0x1UL << HPSYS_RCC_DLL1CR_XTALIN_EN_Pos)
#define HPSYS_RCC_DLL1CR_XTALIN_EN      HPSYS_RCC_DLL1CR_XTALIN_EN_Msk
#define HPSYS_RCC_DLL1CR_MODE48M_EN_Pos  (7U)
#define HPSYS_RCC_DLL1CR_MODE48M_EN_Msk  (0x1UL << HPSYS_RCC_DLL1CR_MODE48M_EN_Pos)
#define HPSYS_RCC_DLL1CR_MODE48M_EN     HPSYS_RCC_DLL1CR_MODE48M_EN_Msk
#define HPSYS_RCC_DLL1CR_LDO_VREF_Pos   (8U)
#define HPSYS_RCC_DLL1CR_LDO_VREF_Msk   (0xFUL << HPSYS_RCC_DLL1CR_LDO_VREF_Pos)
#define HPSYS_RCC_DLL1CR_LDO_VREF       HPSYS_RCC_DLL1CR_LDO_VREF_Msk
#define HPSYS_RCC_DLL1CR_IN_DIV2_EN_Pos  (12U)
#define HPSYS_RCC_DLL1CR_IN_DIV2_EN_Msk  (0x1UL << HPSYS_RCC_DLL1CR_IN_DIV2_EN_Pos)
#define HPSYS_RCC_DLL1CR_IN_DIV2_EN     HPSYS_RCC_DLL1CR_IN_DIV2_EN_Msk
#define HPSYS_RCC_DLL1CR_OUT_DIV2_EN_Pos  (13U)
#define HPSYS_RCC_DLL1CR_OUT_DIV2_EN_Msk  (0x1UL << HPSYS_RCC_DLL1CR_OUT_DIV2_EN_Pos)
#define HPSYS_RCC_DLL1CR_OUT_DIV2_EN    HPSYS_RCC_DLL1CR_OUT_DIV2_EN_Msk
#define HPSYS_RCC_DLL1CR_MCU_PRCHG_EN_Pos  (14U)
#define HPSYS_RCC_DLL1CR_MCU_PRCHG_EN_Msk  (0x1UL << HPSYS_RCC_DLL1CR_MCU_PRCHG_EN_Pos)
#define HPSYS_RCC_DLL1CR_MCU_PRCHG_EN   HPSYS_RCC_DLL1CR_MCU_PRCHG_EN_Msk
#define HPSYS_RCC_DLL1CR_MCU_PRCHG_Pos  (15U)
#define HPSYS_RCC_DLL1CR_MCU_PRCHG_Msk  (0x1UL << HPSYS_RCC_DLL1CR_MCU_PRCHG_Pos)
#define HPSYS_RCC_DLL1CR_MCU_PRCHG      HPSYS_RCC_DLL1CR_MCU_PRCHG_Msk
#define HPSYS_RCC_DLL1CR_PRCHG_EN_Pos   (16U)
#define HPSYS_RCC_DLL1CR_PRCHG_EN_Msk   (0x1UL << HPSYS_RCC_DLL1CR_PRCHG_EN_Pos)
#define HPSYS_RCC_DLL1CR_PRCHG_EN       HPSYS_RCC_DLL1CR_PRCHG_EN_Msk
#define HPSYS_RCC_DLL1CR_PRCHG_EXT_Pos  (17U)
#define HPSYS_RCC_DLL1CR_PRCHG_EXT_Msk  (0x1UL << HPSYS_RCC_DLL1CR_PRCHG_EXT_Pos)
#define HPSYS_RCC_DLL1CR_PRCHG_EXT      HPSYS_RCC_DLL1CR_PRCHG_EXT_Msk
#define HPSYS_RCC_DLL1CR_VST_SEL_Pos    (18U)
#define HPSYS_RCC_DLL1CR_VST_SEL_Msk    (0x1UL << HPSYS_RCC_DLL1CR_VST_SEL_Pos)
#define HPSYS_RCC_DLL1CR_VST_SEL        HPSYS_RCC_DLL1CR_VST_SEL_Msk
#define HPSYS_RCC_DLL1CR_BYPASS_Pos     (19U)
#define HPSYS_RCC_DLL1CR_BYPASS_Msk     (0x1UL << HPSYS_RCC_DLL1CR_BYPASS_Pos)
#define HPSYS_RCC_DLL1CR_BYPASS         HPSYS_RCC_DLL1CR_BYPASS_Msk
#define HPSYS_RCC_DLL1CR_DTEST_EN_Pos   (20U)
#define HPSYS_RCC_DLL1CR_DTEST_EN_Msk   (0x1UL << HPSYS_RCC_DLL1CR_DTEST_EN_Pos)
#define HPSYS_RCC_DLL1CR_DTEST_EN       HPSYS_RCC_DLL1CR_DTEST_EN_Msk
#define HPSYS_RCC_DLL1CR_DTEST_TR_Pos   (21U)
#define HPSYS_RCC_DLL1CR_DTEST_TR_Msk   (0xFUL << HPSYS_RCC_DLL1CR_DTEST_TR_Pos)
#define HPSYS_RCC_DLL1CR_DTEST_TR       HPSYS_RCC_DLL1CR_DTEST_TR_Msk
#define HPSYS_RCC_DLL1CR_PU_DLY_Pos     (25U)
#define HPSYS_RCC_DLL1CR_PU_DLY_Msk     (0x7UL << HPSYS_RCC_DLL1CR_PU_DLY_Pos)
#define HPSYS_RCC_DLL1CR_PU_DLY         HPSYS_RCC_DLL1CR_PU_DLY_Msk
#define HPSYS_RCC_DLL1CR_LOCK_DLY_Pos   (28U)
#define HPSYS_RCC_DLL1CR_LOCK_DLY_Msk   (0x7UL << HPSYS_RCC_DLL1CR_LOCK_DLY_Pos)
#define HPSYS_RCC_DLL1CR_LOCK_DLY       HPSYS_RCC_DLL1CR_LOCK_DLY_Msk
#define HPSYS_RCC_DLL1CR_READY_Pos      (31U)
#define HPSYS_RCC_DLL1CR_READY_Msk      (0x1UL << HPSYS_RCC_DLL1CR_READY_Pos)
#define HPSYS_RCC_DLL1CR_READY          HPSYS_RCC_DLL1CR_READY_Msk

/**************** Bit definition for HPSYS_RCC_DLL2CR register ****************/
#define HPSYS_RCC_DLL2CR_EN_Pos         (0U)
#define HPSYS_RCC_DLL2CR_EN_Msk         (0x1UL << HPSYS_RCC_DLL2CR_EN_Pos)
#define HPSYS_RCC_DLL2CR_EN             HPSYS_RCC_DLL2CR_EN_Msk
#define HPSYS_RCC_DLL2CR_SW_Pos         (1U)
#define HPSYS_RCC_DLL2CR_SW_Msk         (0x1UL << HPSYS_RCC_DLL2CR_SW_Pos)
#define HPSYS_RCC_DLL2CR_SW             HPSYS_RCC_DLL2CR_SW_Msk
#define HPSYS_RCC_DLL2CR_STG_Pos        (2U)
#define HPSYS_RCC_DLL2CR_STG_Msk        (0xFUL << HPSYS_RCC_DLL2CR_STG_Pos)
#define HPSYS_RCC_DLL2CR_STG            HPSYS_RCC_DLL2CR_STG_Msk
#define HPSYS_RCC_DLL2CR_XTALIN_EN_Pos  (6U)
#define HPSYS_RCC_DLL2CR_XTALIN_EN_Msk  (0x1UL << HPSYS_RCC_DLL2CR_XTALIN_EN_Pos)
#define HPSYS_RCC_DLL2CR_XTALIN_EN      HPSYS_RCC_DLL2CR_XTALIN_EN_Msk
#define HPSYS_RCC_DLL2CR_MODE48M_EN_Pos  (7U)
#define HPSYS_RCC_DLL2CR_MODE48M_EN_Msk  (0x1UL << HPSYS_RCC_DLL2CR_MODE48M_EN_Pos)
#define HPSYS_RCC_DLL2CR_MODE48M_EN     HPSYS_RCC_DLL2CR_MODE48M_EN_Msk
#define HPSYS_RCC_DLL2CR_LDO_VREF_Pos   (8U)
#define HPSYS_RCC_DLL2CR_LDO_VREF_Msk   (0xFUL << HPSYS_RCC_DLL2CR_LDO_VREF_Pos)
#define HPSYS_RCC_DLL2CR_LDO_VREF       HPSYS_RCC_DLL2CR_LDO_VREF_Msk
#define HPSYS_RCC_DLL2CR_IN_DIV2_EN_Pos  (12U)
#define HPSYS_RCC_DLL2CR_IN_DIV2_EN_Msk  (0x1UL << HPSYS_RCC_DLL2CR_IN_DIV2_EN_Pos)
#define HPSYS_RCC_DLL2CR_IN_DIV2_EN     HPSYS_RCC_DLL2CR_IN_DIV2_EN_Msk
#define HPSYS_RCC_DLL2CR_OUT_DIV2_EN_Pos  (13U)
#define HPSYS_RCC_DLL2CR_OUT_DIV2_EN_Msk  (0x1UL << HPSYS_RCC_DLL2CR_OUT_DIV2_EN_Pos)
#define HPSYS_RCC_DLL2CR_OUT_DIV2_EN    HPSYS_RCC_DLL2CR_OUT_DIV2_EN_Msk
#define HPSYS_RCC_DLL2CR_MCU_PRCHG_EN_Pos  (14U)
#define HPSYS_RCC_DLL2CR_MCU_PRCHG_EN_Msk  (0x1UL << HPSYS_RCC_DLL2CR_MCU_PRCHG_EN_Pos)
#define HPSYS_RCC_DLL2CR_MCU_PRCHG_EN   HPSYS_RCC_DLL2CR_MCU_PRCHG_EN_Msk
#define HPSYS_RCC_DLL2CR_MCU_PRCHG_Pos  (15U)
#define HPSYS_RCC_DLL2CR_MCU_PRCHG_Msk  (0x1UL << HPSYS_RCC_DLL2CR_MCU_PRCHG_Pos)
#define HPSYS_RCC_DLL2CR_MCU_PRCHG      HPSYS_RCC_DLL2CR_MCU_PRCHG_Msk
#define HPSYS_RCC_DLL2CR_PRCHG_EN_Pos   (16U)
#define HPSYS_RCC_DLL2CR_PRCHG_EN_Msk   (0x1UL << HPSYS_RCC_DLL2CR_PRCHG_EN_Pos)
#define HPSYS_RCC_DLL2CR_PRCHG_EN       HPSYS_RCC_DLL2CR_PRCHG_EN_Msk
#define HPSYS_RCC_DLL2CR_PRCHG_EXT_Pos  (17U)
#define HPSYS_RCC_DLL2CR_PRCHG_EXT_Msk  (0x1UL << HPSYS_RCC_DLL2CR_PRCHG_EXT_Pos)
#define HPSYS_RCC_DLL2CR_PRCHG_EXT      HPSYS_RCC_DLL2CR_PRCHG_EXT_Msk
#define HPSYS_RCC_DLL2CR_VST_SEL_Pos    (18U)
#define HPSYS_RCC_DLL2CR_VST_SEL_Msk    (0x1UL << HPSYS_RCC_DLL2CR_VST_SEL_Pos)
#define HPSYS_RCC_DLL2CR_VST_SEL        HPSYS_RCC_DLL2CR_VST_SEL_Msk
#define HPSYS_RCC_DLL2CR_BYPASS_Pos     (19U)
#define HPSYS_RCC_DLL2CR_BYPASS_Msk     (0x1UL << HPSYS_RCC_DLL2CR_BYPASS_Pos)
#define HPSYS_RCC_DLL2CR_BYPASS         HPSYS_RCC_DLL2CR_BYPASS_Msk
#define HPSYS_RCC_DLL2CR_DTEST_EN_Pos   (20U)
#define HPSYS_RCC_DLL2CR_DTEST_EN_Msk   (0x1UL << HPSYS_RCC_DLL2CR_DTEST_EN_Pos)
#define HPSYS_RCC_DLL2CR_DTEST_EN       HPSYS_RCC_DLL2CR_DTEST_EN_Msk
#define HPSYS_RCC_DLL2CR_DTEST_TR_Pos   (21U)
#define HPSYS_RCC_DLL2CR_DTEST_TR_Msk   (0xFUL << HPSYS_RCC_DLL2CR_DTEST_TR_Pos)
#define HPSYS_RCC_DLL2CR_DTEST_TR       HPSYS_RCC_DLL2CR_DTEST_TR_Msk
#define HPSYS_RCC_DLL2CR_PU_DLY_Pos     (25U)
#define HPSYS_RCC_DLL2CR_PU_DLY_Msk     (0x7UL << HPSYS_RCC_DLL2CR_PU_DLY_Pos)
#define HPSYS_RCC_DLL2CR_PU_DLY         HPSYS_RCC_DLL2CR_PU_DLY_Msk
#define HPSYS_RCC_DLL2CR_LOCK_DLY_Pos   (28U)
#define HPSYS_RCC_DLL2CR_LOCK_DLY_Msk   (0x7UL << HPSYS_RCC_DLL2CR_LOCK_DLY_Pos)
#define HPSYS_RCC_DLL2CR_LOCK_DLY       HPSYS_RCC_DLL2CR_LOCK_DLY_Msk
#define HPSYS_RCC_DLL2CR_READY_Pos      (31U)
#define HPSYS_RCC_DLL2CR_READY_Msk      (0x1UL << HPSYS_RCC_DLL2CR_READY_Pos)
#define HPSYS_RCC_DLL2CR_READY          HPSYS_RCC_DLL2CR_READY_Msk

/*************** Bit definition for HPSYS_RCC_HRCCAL1 register ****************/
#define HPSYS_RCC_HRCCAL1_CAL_LENGTH_Pos  (0U)
#define HPSYS_RCC_HRCCAL1_CAL_LENGTH_Msk  (0xFFFFUL << HPSYS_RCC_HRCCAL1_CAL_LENGTH_Pos)
#define HPSYS_RCC_HRCCAL1_CAL_LENGTH    HPSYS_RCC_HRCCAL1_CAL_LENGTH_Msk
#define HPSYS_RCC_HRCCAL1_CAL_EN_Pos    (30U)
#define HPSYS_RCC_HRCCAL1_CAL_EN_Msk    (0x1UL << HPSYS_RCC_HRCCAL1_CAL_EN_Pos)
#define HPSYS_RCC_HRCCAL1_CAL_EN        HPSYS_RCC_HRCCAL1_CAL_EN_Msk
#define HPSYS_RCC_HRCCAL1_CAL_DONE_Pos  (31U)
#define HPSYS_RCC_HRCCAL1_CAL_DONE_Msk  (0x1UL << HPSYS_RCC_HRCCAL1_CAL_DONE_Pos)
#define HPSYS_RCC_HRCCAL1_CAL_DONE      HPSYS_RCC_HRCCAL1_CAL_DONE_Msk

/*************** Bit definition for HPSYS_RCC_HRCCAL2 register ****************/
#define HPSYS_RCC_HRCCAL2_HRC_CNT_Pos   (0U)
#define HPSYS_RCC_HRCCAL2_HRC_CNT_Msk   (0xFFFFUL << HPSYS_RCC_HRCCAL2_HRC_CNT_Pos)
#define HPSYS_RCC_HRCCAL2_HRC_CNT       HPSYS_RCC_HRCCAL2_HRC_CNT_Msk
#define HPSYS_RCC_HRCCAL2_HXT_CNT_Pos   (16U)
#define HPSYS_RCC_HRCCAL2_HXT_CNT_Msk   (0xFFFFUL << HPSYS_RCC_HRCCAL2_HXT_CNT_Pos)
#define HPSYS_RCC_HRCCAL2_HXT_CNT       HPSYS_RCC_HRCCAL2_HXT_CNT_Msk

/*************** Bit definition for HPSYS_RCC_DBGCLKR register ****************/
#define HPSYS_RCC_DBGCLKR_CLK_SEL_Pos   (0U)
#define HPSYS_RCC_DBGCLKR_CLK_SEL_Msk   (0x3UL << HPSYS_RCC_DBGCLKR_CLK_SEL_Pos)
#define HPSYS_RCC_DBGCLKR_CLK_SEL       HPSYS_RCC_DBGCLKR_CLK_SEL_Msk
#define HPSYS_RCC_DBGCLKR_CLK_EN_Pos    (2U)
#define HPSYS_RCC_DBGCLKR_CLK_EN_Msk    (0x1UL << HPSYS_RCC_DBGCLKR_CLK_EN_Pos)
#define HPSYS_RCC_DBGCLKR_CLK_EN        HPSYS_RCC_DBGCLKR_CLK_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_DBG_Pos  (4U)
#define HPSYS_RCC_DBGCLKR_DLL1_DBG_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL1_DBG_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_DBG      HPSYS_RCC_DBGCLKR_DLL1_DBG_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_LDO_EN_Pos  (5U)
#define HPSYS_RCC_DBGCLKR_DLL1_LDO_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL1_LDO_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_LDO_EN   HPSYS_RCC_DBGCLKR_DLL1_LDO_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_EN_Pos  (6U)
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL1_OUT_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_EN   HPSYS_RCC_DBGCLKR_DLL1_OUT_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_LOOP_EN_Pos  (7U)
#define HPSYS_RCC_DBGCLKR_DLL1_LOOP_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL1_LOOP_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_LOOP_EN  HPSYS_RCC_DBGCLKR_DLL1_LOOP_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_RSTB_Pos  (8U)
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_RSTB_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL1_OUT_RSTB_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_RSTB  HPSYS_RCC_DBGCLKR_DLL1_OUT_RSTB_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_CG_EN_Pos  (9U)
#define HPSYS_RCC_DBGCLKR_DLL1_CG_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL1_CG_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_CG_EN    HPSYS_RCC_DBGCLKR_DLL1_CG_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_STR_Pos  (10U)
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_STR_Msk  (0x3UL << HPSYS_RCC_DBGCLKR_DLL1_OUT_STR_Pos)
#define HPSYS_RCC_DBGCLKR_DLL1_OUT_STR  HPSYS_RCC_DBGCLKR_DLL1_OUT_STR_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_DBG_Pos  (12U)
#define HPSYS_RCC_DBGCLKR_DLL2_DBG_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL2_DBG_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_DBG      HPSYS_RCC_DBGCLKR_DLL2_DBG_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_LDO_EN_Pos  (13U)
#define HPSYS_RCC_DBGCLKR_DLL2_LDO_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL2_LDO_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_LDO_EN   HPSYS_RCC_DBGCLKR_DLL2_LDO_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_EN_Pos  (14U)
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL2_OUT_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_EN   HPSYS_RCC_DBGCLKR_DLL2_OUT_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_LOOP_EN_Pos  (15U)
#define HPSYS_RCC_DBGCLKR_DLL2_LOOP_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL2_LOOP_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_LOOP_EN  HPSYS_RCC_DBGCLKR_DLL2_LOOP_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_RSTB_Pos  (16U)
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_RSTB_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL2_OUT_RSTB_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_RSTB  HPSYS_RCC_DBGCLKR_DLL2_OUT_RSTB_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_CG_EN_Pos  (17U)
#define HPSYS_RCC_DBGCLKR_DLL2_CG_EN_Msk  (0x1UL << HPSYS_RCC_DBGCLKR_DLL2_CG_EN_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_CG_EN    HPSYS_RCC_DBGCLKR_DLL2_CG_EN_Msk
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_STR_Pos  (18U)
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_STR_Msk  (0x3UL << HPSYS_RCC_DBGCLKR_DLL2_OUT_STR_Pos)
#define HPSYS_RCC_DBGCLKR_DLL2_OUT_STR  HPSYS_RCC_DBGCLKR_DLL2_OUT_STR_Msk

/***************** Bit definition for HPSYS_RCC_DBGR register *****************/
#define HPSYS_RCC_DBGR_SYSCLK_AON_Pos   (0U)
#define HPSYS_RCC_DBGR_SYSCLK_AON_Msk   (0x1UL << HPSYS_RCC_DBGR_SYSCLK_AON_Pos)
#define HPSYS_RCC_DBGR_SYSCLK_AON       HPSYS_RCC_DBGR_SYSCLK_AON_Msk
#define HPSYS_RCC_DBGR_SYSCLK_SWLP_Pos  (1U)
#define HPSYS_RCC_DBGR_SYSCLK_SWLP_Msk  (0x1UL << HPSYS_RCC_DBGR_SYSCLK_SWLP_Pos)
#define HPSYS_RCC_DBGR_SYSCLK_SWLP      HPSYS_RCC_DBGR_SYSCLK_SWLP_Msk
#define HPSYS_RCC_DBGR_FORCE_HP_Pos     (4U)
#define HPSYS_RCC_DBGR_FORCE_HP_Msk     (0x1UL << HPSYS_RCC_DBGR_FORCE_HP_Pos)
#define HPSYS_RCC_DBGR_FORCE_HP         HPSYS_RCC_DBGR_FORCE_HP_Msk

/**************** Bit definition for HPSYS_RCC_DWCFGR register ****************/
#define HPSYS_RCC_DWCFGR_HDIV_Pos       (0U)
#define HPSYS_RCC_DWCFGR_HDIV_Msk       (0xFFUL << HPSYS_RCC_DWCFGR_HDIV_Pos)
#define HPSYS_RCC_DWCFGR_HDIV           HPSYS_RCC_DWCFGR_HDIV_Msk
#define HPSYS_RCC_DWCFGR_PDIV1_Pos      (8U)
#define HPSYS_RCC_DWCFGR_PDIV1_Msk      (0x7UL << HPSYS_RCC_DWCFGR_PDIV1_Pos)
#define HPSYS_RCC_DWCFGR_PDIV1          HPSYS_RCC_DWCFGR_PDIV1_Msk
#define HPSYS_RCC_DWCFGR_PDIV2_Pos      (12U)
#define HPSYS_RCC_DWCFGR_PDIV2_Msk      (0x7UL << HPSYS_RCC_DWCFGR_PDIV2_Pos)
#define HPSYS_RCC_DWCFGR_PDIV2          HPSYS_RCC_DWCFGR_PDIV2_Msk
#define HPSYS_RCC_DWCFGR_DIV_EN_Pos     (15U)
#define HPSYS_RCC_DWCFGR_DIV_EN_Msk     (0x1UL << HPSYS_RCC_DWCFGR_DIV_EN_Pos)
#define HPSYS_RCC_DWCFGR_DIV_EN         HPSYS_RCC_DWCFGR_DIV_EN_Msk
#define HPSYS_RCC_DWCFGR_SEL_SYS_Pos    (16U)
#define HPSYS_RCC_DWCFGR_SEL_SYS_Msk    (0x3UL << HPSYS_RCC_DWCFGR_SEL_SYS_Pos)
#define HPSYS_RCC_DWCFGR_SEL_SYS        HPSYS_RCC_DWCFGR_SEL_SYS_Msk
#define HPSYS_RCC_DWCFGR_SEL_SYS_LP_Pos  (18U)
#define HPSYS_RCC_DWCFGR_SEL_SYS_LP_Msk  (0x1UL << HPSYS_RCC_DWCFGR_SEL_SYS_LP_Pos)
#define HPSYS_RCC_DWCFGR_SEL_SYS_LP     HPSYS_RCC_DWCFGR_SEL_SYS_LP_Msk
#define HPSYS_RCC_DWCFGR_DLL1_OUT_EN_Pos  (24U)
#define HPSYS_RCC_DWCFGR_DLL1_OUT_EN_Msk  (0x1UL << HPSYS_RCC_DWCFGR_DLL1_OUT_EN_Pos)
#define HPSYS_RCC_DWCFGR_DLL1_OUT_EN    HPSYS_RCC_DWCFGR_DLL1_OUT_EN_Msk
#define HPSYS_RCC_DWCFGR_DLL1_OUT_RSTB_Pos  (25U)
#define HPSYS_RCC_DWCFGR_DLL1_OUT_RSTB_Msk  (0x1UL << HPSYS_RCC_DWCFGR_DLL1_OUT_RSTB_Pos)
#define HPSYS_RCC_DWCFGR_DLL1_OUT_RSTB  HPSYS_RCC_DWCFGR_DLL1_OUT_RSTB_Msk
#define HPSYS_RCC_DWCFGR_DLL2_OUT_EN_Pos  (26U)
#define HPSYS_RCC_DWCFGR_DLL2_OUT_EN_Msk  (0x1UL << HPSYS_RCC_DWCFGR_DLL2_OUT_EN_Pos)
#define HPSYS_RCC_DWCFGR_DLL2_OUT_EN    HPSYS_RCC_DWCFGR_DLL2_OUT_EN_Msk
#define HPSYS_RCC_DWCFGR_DLL2_OUT_RSTB_Pos  (27U)
#define HPSYS_RCC_DWCFGR_DLL2_OUT_RSTB_Msk  (0x1UL << HPSYS_RCC_DWCFGR_DLL2_OUT_RSTB_Pos)
#define HPSYS_RCC_DWCFGR_DLL2_OUT_RSTB  HPSYS_RCC_DWCFGR_DLL2_OUT_RSTB_Msk

/**************** Bit definition for HPSYS_RCC_TESTR register *****************/
#define HPSYS_RCC_TESTR_SCAN_MODE_Pos   (0U)
#define HPSYS_RCC_TESTR_SCAN_MODE_Msk   (0xFFFFFFFFUL << HPSYS_RCC_TESTR_SCAN_MODE_Pos)
#define HPSYS_RCC_TESTR_SCAN_MODE       HPSYS_RCC_TESTR_SCAN_MODE_Msk

#endif